name: Python CI/CD Pipeline

on:
  pull_request:
    branches:
      - main
      - dev
  schedule:
    - cron: '0 0 * * 0'  # Wekelijkse scans op zondag

jobs:
  sast:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bandit safety detect-secrets

      - name: SAST (Static Analysis)
        run: |
          bandit -r . --quiet

      - name: Dependency Scan
        run: |
          safety check --full-report

      - name: Secrets Scan
        run: |
          detect-secrets scan > .secrets.baseline
          detect-secrets audit .secrets.baseline
      - name: Fail on warnings
        run: |
          bandit -r . --quiet || exit 1
          safety check --full-report || exit 1
          detect-secrets scan > .secrets.baseline || exit 1
